export * from './Contact';
export * from './Home/components/CategoriesProducts';
export * from './Home/components/CategoriesProducts/styled-component/categoriesProducts.styled';
export * from './Home/components/IconsBox';
export * from './Home/components/IconsBox/styled-component/iconsBox.styled';
export * from './Home/components/MensageHome';
export * from './Home/components/MensageHome/styled-components/mensageHome.styled';
export * from './Home';
export * from './Home/styled-components/home.styled';
